### ISSUE TITLE
Dashboard Control Interface Update

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#171]

**Comment by brooksmtownsend** [comment]
We'll also want to re-evaluate the metrics that we show at the top of the page as they are local-host specific and don't belong on a lattice view. We should consider only showing them for the local wasmcloud host, or hiding them altogether for now if they are misleading.

**Comment by brooksmtownsend** [comment]
Notes from community meeting for fixes

- [ ] Show host selector by the breadcrumb

**widgets (some items here are out of scope for 0.50)**
- [x] - Change processes to `Running Processes (OTP)` to avoid confusion
- [ ] - may only care about wasmcloud actor count, rather than OTP processes
- [ ] - Overall vote: Metrics tab with higher fidelity metrics over time
- [ ] - OneView to see overall observability when metrics are useful
- [ ] - Tone down the metrics widget colors

**actors, providers, ldfs**
- [ ] - Show Provider name (requires it to be stored in the claims information)
