### ISSUE TITLE
Support remaining control interface operations in dashboard

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#195]
Below is an incomplete list of operations we can use in the dashboard

- [x] Delete link defininitions https://github.com/wasmCloud/control-interface/issues/3
- [ ] Query oci references (tab with a display table) https://github.com/wasmCloud/control-interface/issues/5
- [ ] Watch CloudEvents (Events tab) https://github.com/wasmCloud/control-interface/issues/4
